runtime: python39  # Use the latest Python runtime
entrypoint: streamlit run app.py

env_variables:
  GOOGLE_TRANSLATE_API_KEY: "your-secured-google-api-key"
  YOUTUBE_API_KEY: "your-secured-youtube-api-key"

handlers:
  - url: /.*
    script: auto
